import { getIVXOwnerVariableRuntimeValue } from '../api/ivx-owner-variables';
import { REQUIRED_CERTIFICATION_WORKFLOWS, runGlobalCertificationSupervision } from './ivx-global-certification-supervisor';

export const IVX_GITHUB_ACTIONS_EXTERNAL_SUPERVISOR_MARKER = 'ivx-github-actions-external-supervisor-v4-cert-lane-2026-08-30';
export const IVX_AUTONOMOUS_ORGANISM_MARKER = 'ivx-autonomous-organism-v2-2026-08-30';
const REPO=process.env.IVX_GITHUB_REPO||'ibb142/ivx-holdings-platform'; const API='https://api.github.com'; const API_BASE=(process.env.IVX_API_BASE||'https://api.ivxholding.com').replace(/\/$/,'');
const INTERVAL_MS=60_000, QUEUE_STORM_THRESHOLD=12, MAX_QUEUE_AGE_MS=5*60_000, CERT_WINDOW_MS=30*60_000, MAX_PAGES=5, CANCEL_CONCURRENCY=8;
const EXTERNAL_TARGETS=['https://ivxholding.com','https://www.ivxholding.com','https://chat.ivxholding.com',`${API_BASE}/health`,`${API_BASE}/version`];
const CRITICAL_WORKFLOWS=new Set<string>([...REQUIRED_CERTIFICATION_WORKFLOWS.map(x=>x.name),'IVX Dashboard + IA Chat End-to-End Certificate','IVX Owner Sign In + Home Android Certificate','IVX 10/10 Full Certification']);
type WorkflowRun={id:number;name:string;event:string;status:string;conclusion:string|null;head_sha:string;head_branch:string|null;created_at:string;updated_at:string}; type Probe={target:string;ok:boolean;status:number|null;latencyMs:number;error:string|null};
export type OrganismSnapshot={marker:typeof IVX_AUTONOMOUS_ORGANISM_MARKER;overall:'GREEN'|'YELLOW'|'RED';brain:{ok:boolean;mainSha:string|null;certification:string|null;error:string|null};heart:{ok:boolean;health:Probe;version:Probe};circulation:{ok:boolean;agents:Probe;dashboard:Probe};senses:{ok:boolean;targets:Probe[]};immune:{ok:boolean;queueStorm:boolean;queued:number;inProgress:number;cancelledRunIds:number[];certificationLaneActive:boolean;windowExpired:boolean;error:string|null}};
export type QueueSnapshot={checkedAt:string;mainSha:string|null;queued:number;inProgress:number;oldestQueuedAgeMs:number;storm:boolean;cancelledRunIds:number[];preservedCriticalRunIds:number[];tokenAvailable:boolean;certificationLaneActive:boolean;certificationWindowStartedAt:string|null;certificationWindowExpired:boolean;error:string|null;organism:OrganismSnapshot|null};
let lastSnapshot:QueueSnapshot|null=null,running=false,cycleRunning=false,timer:ReturnType<typeof setInterval>|null=null,certWindowSha:string|null=null,certWindowStartedAt=0;
async function getToken(){return(process.env.GITHUB_TOKEN||process.env.IVX_GITHUB_TOKEN||(await getIVXOwnerVariableRuntimeValue('GITHUB_TOKEN'))||'').trim();}
async function gh<T>(path:string,token:string,init:RequestInit={}):Promise<T>{const headers:Record<string,string>={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(init.headers as Record<string,string>|undefined)};if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch(`${API}${path}`,{...init,headers,signal:AbortSignal.timeout(10_000)});if(!r.ok)throw new Error(`GitHub ${init.method||'GET'} ${path} -> HTTP ${r.status}`);if(r.status===204)return undefined as T;return await r.json() as T;}
async function listRuns(status:'queued'|'in_progress',token:string){const out:WorkflowRun[]=[];for(let page=1;page<=MAX_PAGES;page++){const d=await gh<{workflow_runs:WorkflowRun[]}>(`/repos/${REPO}/actions/runs?branch=main&status=${status}&per_page=100&page=${page}`,token);out.push(...(d.workflow_runs||[]));if((d.workflow_runs||[]).length<100)break;}return out;}
async function probe(target:string):Promise<Probe>{const s=Date.now();try{const r=await fetch(target,{signal:AbortSignal.timeout(10_000),redirect:'follow',headers:{'User-Agent':'IVX-Autonomous-Organism/2.0'}});return{target,ok:r.ok,status:r.status,latencyMs:Date.now()-s,error:null};}catch(e){return{target,ok:false,status:null,latencyMs:Date.now()-s,error:e instanceof Error?e.message:String(e)}}}
function ageMs(v:string){const n=Date.parse(v);return Number.isFinite(n)?Math.max(0,Date.now()-n):0;} function critical(run:WorkflowRun,sha:string|null){return Boolean(sha&&run.head_branch==='main'&&run.head_sha===sha&&CRITICAL_WORKFLOWS.has(run.name));}
async function cancelRun(id:number,token:string){if(!token)return false;try{await gh<void>(`/repos/${REPO}/actions/runs/${id}/cancel`,token,{method:'POST'});return true;}catch{return false;}}
async function cancelBatch(runs:WorkflowRun[],token:string){const ids:number[]=[];for(let i=0;i<runs.length;i+=CANCEL_CONCURRENCY){const batch=runs.slice(i,i+CANCEL_CONCURRENCY);const results=await Promise.all(batch.map(async r=>({id:r.id,ok:await cancelRun(r.id,token)})));ids.push(...results.filter(x=>x.ok).map(x=>x.id));}return ids;}
async function buildOrganism(mainSha:string|null,queued:number,inProgress:number,storm:boolean,cancelledRunIds:number[],lane:boolean,expired:boolean,queueError:string|null):Promise<OrganismSnapshot>{const external=await Promise.all(EXTERNAL_TARGETS.map(probe));const health=external.find(x=>x.target===`${API_BASE}/health`)!;const version=external.find(x=>x.target===`${API_BASE}/version`)!;const[agents,dashboard]=await Promise.all([probe(`${API_BASE}/api/ivx/agents`),probe(`${API_BASE}/api/ivx/agents/app-completion/dashboard`)]);let certification:string|null=null,brainError:string|null=null;if(mainSha){try{certification=(await runGlobalCertificationSupervision(mainSha)).status;}catch(e){brainError=e instanceof Error?e.message:String(e)}}else brainError='Unable to resolve main SHA.';const heartOk=health.ok&&version.ok,circulationOk=agents.ok&&dashboard.ok,sensesOk=external.every(x=>x.ok),brainOk=Boolean(mainSha&&certification&&certification!=='RED'&&!brainError),immuneOk=!queueError&&!storm&&!expired;const overall:OrganismSnapshot['overall']=(!heartOk||!circulationOk||certification==='RED'||expired)?'RED':(!brainOk||!sensesOk||!immuneOk)?'YELLOW':'GREEN';return{marker:IVX_AUTONOMOUS_ORGANISM_MARKER,overall,brain:{ok:brainOk,mainSha,certification,error:brainError},heart:{ok:heartOk,health,version},circulation:{ok:circulationOk,agents,dashboard},senses:{ok:sensesOk,targets:external},immune:{ok:immuneOk,queueStorm:storm,queued,inProgress,cancelledRunIds,certificationLaneActive:lane,windowExpired:expired,error:queueError}};}
export async function runGitHubActionsExternalSupervision():Promise<QueueSnapshot>{const token=await getToken(),checkedAt=new Date().toISOString(),cancelledRunIds:number[]=[],preservedCriticalRunIds:number[]=[];try{const ref=await gh<{object:{sha:string}}>(`/repos/${REPO}/git/ref/heads/main`,token),mainSha=ref.object.sha||null;let[queued,inProgress]=await Promise.all([listRuns('queued',token),listRuns('in_progress',token)]);const criticalActive=[...queued,...inProgress].some(r=>critical(r,mainSha));if(criticalActive&&certWindowSha!==mainSha){certWindowSha=mainSha;certWindowStartedAt=Date.now();}if(!criticalActive&&certWindowSha===mainSha){certWindowSha=null;certWindowStartedAt=0;}const lane=criticalActive;const expired=Boolean(lane&&certWindowStartedAt&&Date.now()-certWindowStartedAt>CERT_WINDOW_MS);const oldest=queued.reduce((m,r)=>Math.max(m,ageMs(r.created_at)),0);let storm=queued.length>=QUEUE_STORM_THRESHOLD||oldest>=MAX_QUEUE_AGE_MS||lane;
if(storm){const kept=new Set<string>();const disposable:WorkflowRun[]=[];for(const r of [...queued].sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at))){if(critical(r,mainSha)&&!kept.has(r.name)){kept.add(r.name);preservedCriticalRunIds.push(r.id);}else disposable.push(r);}cancelledRunIds.push(...await cancelBatch(disposable,token));const staleRunning=inProgress.filter(r=>mainSha&&r.head_sha!==mainSha&&!CRITICAL_WORKFLOWS.has(r.name));cancelledRunIds.push(...await cancelBatch(staleRunning,token));[queued,inProgress]=await Promise.all([listRuns('queued',token),listRuns('in_progress',token)]);const postOldest=queued.reduce((m,r)=>Math.max(m,ageMs(r.created_at)),0);storm=queued.length>=QUEUE_STORM_THRESHOLD||postOldest>=MAX_QUEUE_AGE_MS;}
const organism=await buildOrganism(mainSha,queued.length,inProgress.length,storm,cancelledRunIds,lane,expired,null);lastSnapshot={checkedAt,mainSha,queued:queued.length,inProgress:inProgress.length,oldestQueuedAgeMs:queued.reduce((m,r)=>Math.max(m,ageMs(r.created_at)),0),storm,cancelledRunIds,preservedCriticalRunIds,tokenAvailable:Boolean(token),certificationLaneActive:lane,certificationWindowStartedAt:certWindowStartedAt?new Date(certWindowStartedAt).toISOString():null,certificationWindowExpired:expired,error:null,organism};console.log('[IVX Autonomous Organism]',{overall:organism.overall,mainSha,lane,expired,queued:queued.length,inProgress:inProgress.length,cancelled:cancelledRunIds.length});return lastSnapshot;}catch(e){const error=e instanceof Error?e.message:String(e);const organism=await buildOrganism(null,0,0,false,cancelledRunIds,false,false,error).catch(()=>null);lastSnapshot={checkedAt,mainSha:null,queued:0,inProgress:0,oldestQueuedAgeMs:0,storm:false,cancelledRunIds,preservedCriticalRunIds,tokenAvailable:Boolean(token),certificationLaneActive:false,certificationWindowStartedAt:null,certificationWindowExpired:false,error,organism};return lastSnapshot;}}
export function getGitHubActionsExternalSupervisorStatus(){return lastSnapshot;} export function getAutonomousOrganismStatus(){return lastSnapshot?.organism||null;}
export function startGitHubActionsExternalSupervisor(){if(running)return;running=true;const execute=async()=>{if(cycleRunning)return;cycleRunning=true;try{await runGitHubActionsExternalSupervision();}finally{cycleRunning=false;}};const boot=setTimeout(()=>void execute(),15_000);boot.unref?.();timer=setInterval(()=>void execute(),INTERVAL_MS);timer.unref?.();}
export function stopGitHubActionsExternalSupervisorForTests(){running=false;cycleRunning=false;certWindowSha=null;certWindowStartedAt=0;if(timer)clearInterval(timer);timer=null;}
