/**
 * IVX Autonomous Intelligence Mission Scheduler (AIMS).
 *
 * One real autonomous engineering mission is started for this scheduler marker.
 * Terminal state is durable across restarts/deploys so the scheduler cannot
 * create an infinite evidence -> merge -> deploy -> evidence loop.
 */
import { randomUUID } from 'node:crypto';
import {
  appendDurableEvent,
  isDurableStoreConfigured,
  readDurableJson,
  writeDurableJson,
} from './ivx-durable-store';
import {
  enqueueOrAttachSeniorDeveloperJob,
  getSeniorDeveloperJob,
  listSeniorDeveloperProofLedger,
  type IVXWorkerJob,
  type IVXWorkerJobResult,
} from './ivx-senior-developer-worker';
import { syncCampaignAssignmentsToDispatcher } from './ivx-app-completion-campaign';
import { runCampaignBootRecovery, startCampaignDispatcher } from './ivx-campaign-dispatcher';

export const IVX_AUTONOMOUS_INTELLIGENCE_MISSION_SCHEDULER_MARKER =
  'ivx-autonomous-intelligence-mission-scheduler-v3-2026-08-25';

const OWNER_ID = 'ivx-autonomous-intelligence-mission-scheduler';
const POLL_INTERVAL_MS = 15_000;
const LIVE_VERIFY_TIMEOUT_MS = 12_000;
const STATE_PATH = 'logs/audit/autonomous-intelligence-mission-scheduler/state.json';
const EVIDENCE_PATH = 'expo/evidence/autonomous/ivx-autonomous-intelligence-mission-scheduler-cert.json';
const DEFAULT_API_BASE = 'https://api.ivxholding.com';

export type MissionSchedulerJobStatus =
  | 'queued'
  | 'running'
  | 'patching'
  | 'testing'
  | 'committing'
  | 'deploying'
  | 'verifying'
  | 'completed'
  | 'failed'
  | 'blocked'
  | 'cancelled'
  | 'unknown';

export type MissionSchedulerState = {
  marker: string;
  startedAt: string;
  schedulerJobId: string;
  deploySha: string | null;
  missionJobId: string | null;
  status: MissionSchedulerJobStatus;
  stage: string | null;
  progressPercent: number;
  stageDetail: string;
  inspectedFiles: string[];
  changedFiles: string[];
  commitSha: string | null;
  prNumber: number | null;
  prUrl: string | null;
  prMerged: boolean | null;
  prMergeCommitSha: string | null;
  deployId: string | null;
  liveCommit: string | null;
  healthOk: boolean | null;
  completedAt: string | null;
  error: string | null;
  updatedAt: string;
};

let currentState: MissionSchedulerState | null = null;
let pollTimer: ReturnType<typeof setInterval> | null = null;

function nowIso(): string {
  return new Date().toISOString();
}

function getCurrentDeploySha(): string | null {
  return (
    process.env.RENDER_GIT_COMMIT?.trim() ||
    process.env.GIT_COMMIT_SHA?.trim() ||
    process.env.SOURCE_VERSION?.trim() ||
    null
  );
}

function getApiBase(): string {
  return (
    process.env.IVX_PUBLIC_API_BASE_URL?.trim() ||
    process.env.IVX_API_BASE_URL?.trim() ||
    DEFAULT_API_BASE
  ).replace(/\/+$/, '');
}

function extractCommit(payload: unknown): string | null {
  if (!payload || typeof payload !== 'object') return null;
  const row = payload as Record<string, unknown>;
  const direct = row.commit;
  if (typeof direct === 'string' && direct.trim()) return direct.trim();
  const version = row.version;
  if (version && typeof version === 'object') {
    const nested = (version as Record<string, unknown>).commit;
    if (typeof nested === 'string' && nested.trim()) return nested.trim();
  }
  return null;
}

function healthPayloadLooksOk(payload: unknown): boolean {
  if (!payload || typeof payload !== 'object') return false;
  const row = payload as Record<string, unknown>;
  if (row.ok === true || row.healthy === true) return true;
  if (typeof row.status === 'string' && ['ok', 'healthy', 'ready'].includes(row.status.toLowerCase())) return true;
  const database = row.database;
  if (database && typeof database === 'object') {
    const db = database as Record<string, unknown>;
    if (db.ok === true || db.healthy === true || db.configured === true) return true;
  }
  return false;
}

/** Host-generated timestamp is embedded literally in the task contract. */
export function buildMissionGoal(createdAt: string): string {
  return `Create a durable autonomous intelligence mission scheduler live evidence file at:
${EVIDENCE_PATH}

The file must contain exactly these fields and exact values:
- "marker": "${IVX_AUTONOMOUS_INTELLIGENCE_MISSION_SCHEDULER_MARKER}"
- "mission": "autonomous intelligence mission scheduler live"
- "createdAt": "${createdAt}"
- "creator": "ivx-senior-developer-worker"

IMPORTANT: createdAt above was generated by the host. Copy it exactly; do not invent, approximate, replace, or rewrite the timestamp.

No other functional code changes. Inspect the existing mission scheduler and worker modules to confirm the marker, run relevant tests and backend typecheck, commit to an autonomous branch, open a PR, wait for required CI to complete successfully, and merge only when CI is green. This is a low-risk evidence-only task.`;
}

export function isTerminalMissionStatus(status: MissionSchedulerJobStatus): boolean {
  return ['completed', 'failed', 'blocked', 'cancelled'].includes(status);
}

/**
 * Pure SHA backfill only. This function does NOT fabricate health success.
 * Explicit /health + /version proof is handled by verifyCurrentProduction().
 */
export function verifyLiveDeployForState(state: MissionSchedulerState): MissionSchedulerState {
  if (state.status !== 'completed' || !state.prMerged || !state.prMergeCommitSha) return state;
  const currentDeploySha = getCurrentDeploySha();
  if (!currentDeploySha || currentDeploySha !== state.prMergeCommitSha) return state;
  const staleResumeError = Boolean(
    state.error &&
      (state.error.includes('no changed files') || state.error.includes('stale evidence')),
  );
  if (state.liveCommit === currentDeploySha && !staleResumeError) return state;
  return {
    ...state,
    liveCommit: currentDeploySha,
    error: staleResumeError ? null : state.error,
    stageDetail:
      state.healthOk === true
        ? 'Mission merged commit is the current production deploy and health evidence is present.'
        : 'Mission merged commit is the current production deploy; explicit /health + /version verification is still required.',
    updatedAt: nowIso(),
  };
}

async function verifyCurrentProduction(state: MissionSchedulerState): Promise<MissionSchedulerState> {
  if (state.status !== 'completed' || !state.prMerged || !state.prMergeCommitSha) return state;
  const currentDeploySha = getCurrentDeploySha();
  if (!currentDeploySha || currentDeploySha !== state.prMergeCommitSha) {
    if (state.healthOk === false && state.liveCommit !== currentDeploySha) return state;
    return {
      ...state,
      healthOk: false,
      stageDetail: 'Mission is complete historically, but the current production deploy is not the mission merge SHA.',
      updatedAt: nowIso(),
    };
  }

  const apiBase = getApiBase();
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), LIVE_VERIFY_TIMEOUT_MS);
  try {
    const [healthResponse, versionResponse] = await Promise.all([
      fetch(`${apiBase}/health`, { signal: controller.signal }),
      fetch(`${apiBase}/version`, { signal: controller.signal }),
    ]);
    const healthBody = await healthResponse.json().catch(() => null);
    const versionBody = await versionResponse.json().catch(() => null);
    const liveCommit = extractCommit(versionBody) ?? extractCommit(healthBody);
    const healthOk =
      healthResponse.ok &&
      versionResponse.ok &&
      healthPayloadLooksOk(healthBody) &&
      liveCommit === currentDeploySha;

    return {
      ...state,
      liveCommit,
      healthOk,
      stageDetail: healthOk
        ? 'Mission completed and verified live with /health + /version exact-SHA proof.'
        : 'Mission merge SHA is deployed, but explicit /health + /version verification did not pass.',
      updatedAt: nowIso(),
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'live verification failed';
    return {
      ...state,
      healthOk: false,
      stageDetail: `Live verification failed closed: ${message.slice(0, 160)}`,
      updatedAt: nowIso(),
    };
  } finally {
    clearTimeout(timeout);
  }
}

function emptyState(): MissionSchedulerState {
  return {
    marker: IVX_AUTONOMOUS_INTELLIGENCE_MISSION_SCHEDULER_MARKER,
    startedAt: nowIso(),
    schedulerJobId: randomUUID(),
    deploySha: getCurrentDeploySha(),
    missionJobId: null,
    status: 'unknown',
    stage: null,
    progressPercent: 0,
    stageDetail: 'Scheduler not yet started.',
    inspectedFiles: [],
    changedFiles: [],
    commitSha: null,
    prNumber: null,
    prUrl: null,
    prMerged: null,
    prMergeCommitSha: null,
    deployId: null,
    liveCommit: null,
    healthOk: null,
    completedAt: null,
    error: null,
    updatedAt: nowIso(),
  };
}

async function loadState(): Promise<MissionSchedulerState> {
  if (isDurableStoreConfigured()) {
    try {
      const parsed = await readDurableJson<MissionSchedulerState | null>(STATE_PATH, null);
      if (parsed && parsed.marker === IVX_AUTONOMOUS_INTELLIGENCE_MISSION_SCHEDULER_MARKER) {
        // Never reset a valid marker simply because a deployment changed.
        // The old behavior created an evidence->merge->deploy->evidence loop.
        return parsed;
      }
    } catch {
      // fall through to a fresh state
    }
  }
  return emptyState();
}

async function saveState(state: MissionSchedulerState): Promise<void> {
  const next: MissionSchedulerState = { ...state, updatedAt: nowIso() };
  currentState = next;
  if (isDurableStoreConfigured()) {
    try {
      await writeDurableJson(STATE_PATH, next);
      await appendDurableEvent(STATE_PATH.replace(/state\.json$/, 'events.jsonl'), {
        type: 'mission_scheduler_state',
        missionJobId: next.missionJobId,
        status: next.status,
        stage: next.stage,
        progressPercent: next.progressPercent,
        stageDetail: next.stageDetail,
        updatedAt: next.updatedAt,
      });
    } catch {
      // durable store best-effort; in-memory state remains authoritative for this process
    }
  }
}

function mapJobStatus(job: IVXWorkerJob): MissionSchedulerJobStatus {
  switch (job.status) {
    case 'queued': return 'queued';
    case 'running': return 'running';
    case 'patching': return 'patching';
    case 'testing': return 'testing';
    case 'committing': return 'committing';
    case 'deploying': return 'deploying';
    case 'verifying': return 'verifying';
    case 'completed': return 'completed';
    case 'failed': return 'failed';
    case 'blocked': return 'blocked';
    case 'cancelled': return 'cancelled';
    default: return 'unknown';
  }
}

function mergeJobIntoState(state: MissionSchedulerState, job: IVXWorkerJob): MissionSchedulerState {
  const result: IVXWorkerJobResult | null = job.result ?? null;
  const inspected = result?.filesInspected ?? [];
  const changed = result?.changedFiles ?? [];
  return {
    ...state,
    missionJobId: job.jobId,
    status: mapJobStatus(job),
    stage: job.stage,
    progressPercent: job.progressPercent,
    stageDetail: job.stageDetail,
    inspectedFiles: inspected.length > 0 ? inspected : state.inspectedFiles,
    changedFiles: changed.length > 0 ? changed : state.changedFiles,
    commitSha: result?.commitSha ?? state.commitSha,
    prNumber: result?.prNumber ?? state.prNumber,
    prUrl: result?.prUrl ?? state.prUrl,
    prMerged: result?.prMerged ?? state.prMerged,
    prMergeCommitSha: result?.prMergeCommitSha ?? state.prMergeCommitSha,
    deployId: result?.deployId ?? state.deployId,
    liveCommit: result?.liveCommit ?? state.liveCommit,
    healthOk: result?.healthOk ?? state.healthOk,
    completedAt: job.status === 'completed' ? (result?.generatedAt ?? nowIso()) : state.completedAt,
    error: job.error ?? (job.status === 'failed' || job.status === 'blocked' ? state.error : null),
    updatedAt: nowIso(),
  };
}

async function refreshMissionJob(): Promise<void> {
  if (!currentState || !currentState.missionJobId) return;
  try {
    const job = await getSeniorDeveloperJob(currentState.missionJobId);
    if (!job) return;
    let next = mergeJobIntoState(currentState, job);
    next = verifyLiveDeployForState(next);
    next = await verifyCurrentProduction(next);
    await saveState(next);
  } catch (error) {
    const message = error instanceof Error ? error.message : 'refresh failed';
    console.warn('[IVX AIMS] refresh failed', { message: message.slice(0, 200) });
  }
}

export function isMissionStateCertified(
  state: MissionSchedulerState,
  workerResult: IVXWorkerJobResult | null,
  currentDeploySha: string | null = getCurrentDeploySha(),
): boolean {
  if (!workerResult || !currentDeploySha) return false;
  return Boolean(
    state.status === 'completed' &&
      state.progressPercent === 100 &&
      !state.error &&
      state.missionJobId &&
      state.prMerged === true &&
      state.prMergeCommitSha &&
      state.liveCommit === state.prMergeCommitSha &&
      currentDeploySha === state.prMergeCommitSha &&
      state.healthOk === true &&
      workerResult.jobId === state.missionJobId &&
      workerResult.ok === true &&
      workerResult.testsRun === true &&
      workerResult.testsPassed === true &&
      workerResult.typecheckRun === true &&
      workerResult.typecheckPassed === true &&
      workerResult.commitCreated === true &&
      Boolean(workerResult.commitSha) &&
      workerResult.prMerged === true &&
      workerResult.ciChecksGreen === true &&
      workerResult.prMergeCommitSha === state.prMergeCommitSha &&
      workerResult.finalStatus === 'COMPLETE' &&
      !workerResult.error
  );
}

/**
 * Start or attach to the one real mission for this scheduler marker.
 *
 * IMPORTANT: the authoritative 112-agent runtime is the campaign dispatcher
 * backed by ivx-senior-developer-worker. That worker is self-draining: enqueue
 * immediately kicks drainSeniorDeveloperQueue(), so AIMS must NOT depend on the
 * unrelated legacy IVX_SENIOR_DEV_WORKER_ENABLED flag used by
 * ivx-senior-dev-worker / ivx_owner_ai_tasks.
 */
export async function startAutonomousIntelligenceMissionScheduler(): Promise<void> {
  console.log('[IVX AIMS] Starting autonomous intelligence mission scheduler...');

  try {
    await syncCampaignAssignmentsToDispatcher();
    const recovered = await runCampaignBootRecovery();
    startCampaignDispatcher();
    console.log('[IVX AIMS] Authoritative 112 runtime bootstrapped', {
      runtime: 'campaign-dispatcher -> ivx-senior-developer-worker',
      recovered,
      legacyWorkerFlagRequired: false,
    });
  } catch (error) {
    console.error('[IVX AIMS] Authoritative 112 runtime bootstrap failed', {
      error: error instanceof Error ? error.message.slice(0, 240) : String(error).slice(0, 240),
    });
  }

  const state = await loadState();
  currentState = state;

  const deploySha = getCurrentDeploySha();
  console.log('[IVX AIMS] Scheduler boot diagnostics', {
    deploySha,
    workerRuntime: 'ivx-senior-developer-worker:self-draining',
    durableStore: isDurableStoreConfigured(),
    existingMissionJobId: state.missionJobId,
    existingStatus: state.status,
  });

  // Terminal jobs are durable. Do not auto-replay them on boot/deploy.
  if (state.missionJobId && isTerminalMissionStatus(state.status)) {
    let terminal = verifyLiveDeployForState(state);
    terminal = await verifyCurrentProduction(terminal);
    await saveState(terminal);
    console.log('[IVX AIMS] Preserving terminal mission state; no duplicate mission enqueued', {
      jobId: state.missionJobId,
      status: state.status,
      currentDeploySha: deploySha,
    });
    return;
  }

  let jobId = state.missionJobId;
  if (jobId) {
    try {
      const existing = await getSeniorDeveloperJob(jobId);
      if (existing && !isTerminalMissionStatus(mapJobStatus(existing))) {
        console.log('[IVX AIMS] Attaching to existing active mission job', { jobId });
        currentState = mergeJobIntoState(currentState, existing);
        await saveState(currentState);
      } else if (existing) {
        let terminal = mergeJobIntoState(currentState, existing);
        terminal = verifyLiveDeployForState(terminal);
        terminal = await verifyCurrentProduction(terminal);
        await saveState(terminal);
        console.log('[IVX AIMS] Existing worker job is terminal; preserving it without replay', {
          jobId,
          status: terminal.status,
        });
        return;
      } else {
        jobId = null;
      }
    } catch {
      jobId = null;
    }
  }

  if (!jobId) {
    try {
      const createdAt = nowIso();
      const goal = buildMissionGoal(createdAt);
      const enqueued = await enqueueOrAttachSeniorDeveloperJob({
        goal,
        ownerApproved: true,
        approvePatch: true,
        approveGitDeploy: false,
        validationMode: 'focused',
        systemMode: true,
        ownerApprovedAction: {
          proposedPlan: goal,
          filesAffected: [EVIDENCE_PATH],
          riskLevel: 'low',
          rollbackOption: 'Delete the evidence file and revert the autonomous commit.',
          rollbackAvailable: true,
          auditLog: [
            'Autonomous Intelligence Mission Scheduler boot submission',
            `marker: ${IVX_AUTONOMOUS_INTELLIGENCE_MISSION_SCHEDULER_MARKER}`,
            `hostGeneratedEvidenceTimestamp: ${createdAt}`,
          ],
          secretValuesReturned: false,
        },
        ownerId: OWNER_ID,
        executionMode: 'code_change',
        actor: 'SYSTEM',
      });

      jobId = enqueued.job.jobId;
      currentState = {
        ...currentState,
        missionJobId: jobId,
        status: mapJobStatus(enqueued.job),
        stage: enqueued.job.stage,
        progressPercent: enqueued.job.progressPercent,
        stageDetail: enqueued.job.stageDetail,
        updatedAt: nowIso(),
      };
      await saveState(currentState);
      console.log('[IVX AIMS] Real mission job enqueued', {
        jobId,
        attached: enqueued.attached,
        ownerId: OWNER_ID,
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : 'enqueue failed';
      console.error('[IVX AIMS] Failed to enqueue mission job', { message: message.slice(0, 300) });
      currentState = {
        ...currentState,
        status: 'failed',
        stage: 'FAILED',
        stageDetail: `Mission scheduler failed to enqueue job: ${message.slice(0, 200)}`,
        error: message.slice(0, 300),
        updatedAt: nowIso(),
      };
      await saveState(currentState);
      return;
    }
  }

  await refreshMissionJob();
  if (pollTimer) clearInterval(pollTimer);
  pollTimer = setInterval(() => { void refreshMissionJob(); }, POLL_INTERVAL_MS);
  pollTimer.unref?.();
}

export function stopAutonomousIntelligenceMissionScheduler(): void {
  if (pollTimer) {
    clearInterval(pollTimer);
    pollTimer = null;
  }
  currentState = null;
}

export async function getMissionSchedulerStatus(): Promise<{
  ok: boolean;
  marker: string;
  schedulerJobId: string;
  missionJobId: string | null;
  state: MissionSchedulerState;
  workerResult: IVXWorkerJobResult | null;
}> {
  const state = currentState ?? (await loadState());
  let workerResult: IVXWorkerJobResult | null = null;
  if (state.missionJobId) {
    try {
      const job = await getSeniorDeveloperJob(state.missionJobId);
      if (job?.result) {
        workerResult = job.result;
      } else {
        const ledger = await listSeniorDeveloperProofLedger(100);
        workerResult = ledger.find((entry) => entry.jobId === state.missionJobId) ?? null;
      }
    } catch {
      workerResult = null;
    }
  }

  let verifiedState = verifyLiveDeployForState(state);
  verifiedState = await verifyCurrentProduction(verifiedState);
  if (verifiedState !== state) {
    currentState = verifiedState;
    await saveState(currentState);
  }

  return {
    ok: isMissionStateCertified(verifiedState, workerResult),
    marker: IVX_AUTONOMOUS_INTELLIGENCE_MISSION_SCHEDULER_MARKER,
    schedulerJobId: verifiedState.schedulerJobId,
    missionJobId: verifiedState.missionJobId,
    state: verifiedState,
    workerResult,
  };
}
