// Check all available env vars in the sandbox
const keys = [
  'EXPO_PUBLIC_SUPABASE_URL', 'EXPO_PUBLIC_SUPABASE_ANON_KEY',
  'EXPO_PUBLIC_PROJECT_ID', 'EXPO_PUBLIC_TEAM_ID',
  'EXPO_PUBLIC_RORK_API_BASE_URL', 'EXPO_PUBLIC_RORK_APP_KEY',
  'EXPO_PUBLIC_RORK_AUTH_URL', 'EXPO_PUBLIC_RORK_FUNCTIONS_URL',
  'EXPO_PUBLIC_RORK_TOOLKIT_SECRET_KEY', 'EXPO_PUBLIC_TOOLKIT_URL',
  'RORK_PUBLIC_GITHUB_TOKEN', 'RORK_PUBLIC_IVX_AI_KEY', 'RORK_PUBLIC_IVX_OWNER_EMAIL',
  'SUPABASE_URL', 'IVX_SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY',
  'SUPABASE_ACCESS_TOKEN', 'IVX_OWNER_SUPABASE_ACCESS_TOKEN', 'SUPABASE_DB_URL',
  'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_REGION',
  'CLOUDFRONT_DISTRIBUTION_ID', 'S3_BUCKET_NAME',
  'AI_GATEWAY_API_KEY', 'IVX_AI_GATEWAY_KEY', 'IVX_AI_SYSTEM_SECRET',
  'GITHUB_TOKEN', 'GITHUB_REPO_URL',
  'RENDER_API_KEY', 'IVX_RENDER_API_KEY', 'RENDER_SERVICE_ID',
  'IVX_OWNER_TOKEN', 'IVX_OWNER_TOKEN_SESSION',
  'IVX_OWNER_EMAIL', 'IVX_OWNER_PASSWORD', 'IVX_OWNER_REGISTRATION_EMAILS',
  'IVX_OWNER_RECOVERY_PHONE',
  'IVX_INTERNAL_DEPLOY_SECRET',
  'JWT_SECRET', 'APP_SECRET',
];

for (const k of keys) {
  const v = Bun.env[k] || process.env[k];
  if (v && v.trim()) {
    const masked = v.length > 20 ? v.slice(0,8) + '...' + v.slice(-4) + ' (' + v.length + ' chars)' : 'SET (' + v.length + ' chars)';
    console.log(k + ': ' + masked);
  }
}
console.log('--- end ---');
