import React, { useEffect, useRef } from 'react';
import { Stack } from 'expo-router';
import {View, Text, StyleSheet } from "react-native";
import { useRouter } from 'expo-router';
import Colors from '@/constants/colors';
import { useAuth } from '@/lib/auth-context';
import { isAdminRole } from '@/lib/auth-helpers';
import { isOpenAccessModeEnabled } from '@/lib/open-access';
import { ShimmerIndicator } from '@/components/ShimmerIndicator';
export { ErrorBoundary } from 'expo-router';
const IVX_STACK_SCREEN_OPTIONS={headerStyle:{backgroundColor:Colors.background},headerTintColor:Colors.text,headerTitleStyle:{fontWeight:'700' as const},contentStyle:{backgroundColor:Colors.background},headerShadowVisible:false} as const;
const screens:Record<string,{title:string;headerShown?:boolean}>={inbox:{title:'IVX Inbox'},chat:{title:'IVX Owner AI',headerShown:false},variables:{title:'Variables / Credentials'},independence:{title:'Independence Tracker'},files:{title:'Files & Multimodal'},diagnostics:{title:'IVX Diagnostics'},'production-diagnostics':{title:'Production Diagnostics'},'owner-ai-log':{title:'Owner AI Diagnostics Log'},search:{title:'Search Owner Room'},'cto-dashboard':{title:'CTO Operational Dashboard'},'project-dashboard':{title:'AI Project Dashboard'},'proof-test':{title:'Proof Test'},'durability-proof':{title:'Owner AI Durability Proof'},'proof-ledger':{title:'Senior Developer Proof Ledger'},incidents:{title:'Incidents'},deploy:{title:'Approve & Deploy'},'contact/[id]':{title:'Contact Profile'},'autonomous-scale':{title:'Autonomous Scale Mode'},'autonomous-activity':{title:'Autonomous Activity (24h)'},'master-lead-list':{title:'Master Lead List'},'lead-audit-log':{title:'Lead Audit Log'},'daily-report':{title:'Daily Report'},'github-sync':{title:'Sync to GitHub'},campaign:{title:'Campaign Report'},'autonomous-ops':{title:'Autonomous Operations'},'agent-gps':{title:'IA GPS • 112'},'landing-10of10':{title:'Landing 10/10 • 112 IA'},'landing-war-room-map':{title:'Landing War Room Map'},'agent-command-center':{title:'AI Engineering Command Center'},'agent-ledger':{title:'112 IA • Real Production Ledger'}};
export default function IVXOwnerLayout(){const router=useRouter();const{isAuthenticated,isLoading,userRole}=useAuth();const attempted=useRef(false);useEffect(()=>{if(isLoading||isOpenAccessModeEnabled())return;if(!isAuthenticated&&!attempted.current){attempted.current=true;router.replace('/login')}else if(isAuthenticated&&attempted.current)attempted.current=false},[isAuthenticated,isLoading,router]);if(isLoading)return <View style={st.loading}><ShimmerIndicator size="large" color={Colors.primary}/><Text style={st.loadingText}>Loading IVX…</Text></View>;if(!isAuthenticated||!isAdminRole(userRole))return <View style={st.loading}><Text style={st.denied}>Access denied. Owner/Admin role required.</Text></View>;return <Stack screenOptions={IVX_STACK_SCREEN_OPTIONS}>{Object.entries(screens).map(([name,options])=><Stack.Screen key={name} name={name} options={options}/>)}</Stack>}
const st=StyleSheet.create({loading:{flex:1,backgroundColor:Colors.background,alignItems:'center',justifyContent:'center',padding:24},loadingText:{color:Colors.primary,fontSize:14,fontWeight:'600',marginTop:12},denied:{color:Colors.error,fontSize:14,fontWeight:'600',textAlign:'center'}});