import React, { useCallback, useMemo, useState } from 'react';
import { ScrollView, View, Text, StyleSheet, RefreshControl, Pressable, TextInput } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import Colors from '@/constants/colors';
import { getIVXAccessToken, IVX_CANONICAL_API_BASE_URL } from '@/lib/ivx-supabase-client';

type Totals={totalAgents:number;active:number;idle:number;blocked:number;coding:number;testing:number;waitingCi:number;deploying:number;complete:number;commits24h:number;prs24h:number;merges24h:number;deploys24h:number;agentHours24h:number;idleHours24h:number;idleWithSafeBacklog:number};
type Timer={running:boolean;workStartedAt:string|null;workEndedAt:string|null;currentTaskElapsedHours:number;windowStartAt:string;windowEndAt:string;productiveMs24h:number;productiveHours24h:number;idleMs24h:number;idleHours24h:number;measuredAt:string};
type Agent={agentNumber:number;agentId:string;agentName:string;role:string|null;task:string|null;workstream:string;githubRunId:number|null;prNumber:number|null;commitSha:string|null;deployId:string|null;status:string;blocker:string|null;filesChanged:string[];lastCompletedTask:string|null;productiveMs24h:number;idleMs24h:number;qualityState:string;evidenceState:string;timer:Timer};
type AutonomousTimer={id:string;name:string;status:string;running:boolean;workStartedAt:string|null;workEndedAt:string|null;windowStartAt:string;windowEndAt:string|null;productiveMs24h:number;productiveHours24h:number;idleMs24h:number;idleHours24h:number;coveragePercent24h:number;activeManagedExecutions:number;measuredAt:string;evidencePolicy:string};
type Resp={ok:boolean;marker:string;generatedAt:string;rowCount:number;systemRowCount:number;timerMeasuredAt:string;timerWindow:{startAt:string;endAt:string;durationHours:number};totals:Totals;autonomous:AutonomousTimer;agents:Agent[];policy:string;timerPolicy:string};
type RunRecord={runId:string;agentId:string;agentNumber:number;startTime?:string|null;endTime?:string|null;durationMs?:number|null;finalStatus?:string|null;evidence?:unknown[]};
type RunResp={ok:boolean;records?:RunRecord[];count?:number;totalRecords?:number};
type PeriodKey='1D'|'7D'|'30D'|'90D'|'1Y'|'ALL';
type DayValue={date:string;hours:number;value:number;runs:number};

const sha=(v:string|null)=>v?v.slice(0,8):'—';
const when=(v:string|null)=>v?new Date(v).toLocaleString():'—';
const money=(v:number)=>`$${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const PERIODS:PeriodKey[]=['1D','7D','30D','90D','1Y','ALL'];
const periodStart=(key:PeriodKey)=>{if(key==='ALL')return 0;const days=key==='1D'?1:key==='7D'?7:key==='30D'?30:key==='90D'?90:365;return Date.now()-days*24*60*60*1000;};

async function authHeaders(){const token=await getIVXAccessToken();if(!token)throw new Error('Owner session required.');return {Authorization:`Bearer ${token}`,Accept:'application/json'};}
async function fetchLedger():Promise<Resp>{const r=await fetch(`${IVX_CANONICAL_API_BASE_URL}/api/ivx/autonomous/agent-ledger`,{headers:await authHeaders()});const b=await r.json().catch(()=>({})) as Partial<Resp>&{error?:string};if(!r.ok||b.ok!==true)throw new Error(b.error||`Ledger HTTP ${r.status}`);if(b.rowCount!==112||!Array.isArray(b.agents)||b.agents.length!==112)throw new Error('Ledger integrity failure: expected exactly 112 IA rows.');if(!b.autonomous)throw new Error('Ledger integrity failure: Autonomous timer missing.');return b as Resp;}
async function fetchRuns(agentId:string|null):Promise<RunRecord[]>{const path=agentId?`/api/ivx/agents/runs/${encodeURIComponent(agentId)}?limit=10000`:'/api/ivx/agents/runs?limit=10000';const r=await fetch(`${IVX_CANONICAL_API_BASE_URL}${path}`,{headers:await authHeaders()});const b=await r.json().catch(()=>({})) as RunResp&{error?:string};if(!r.ok||b.ok!==true)throw new Error(b.error||`Run history HTTP ${r.status}`);return Array.isArray(b.records)?b.records:[];}

export default function AgentLedgerScreen(){
  const [selectedAgent,setSelectedAgent]=useState<number|null>(null);const [period,setPeriod]=useState<PeriodKey>('30D');const [rateText,setRateText]=useState('100');
  const q=useQuery({queryKey:['ivx','agent-ledger','live'],queryFn:fetchLedger,refetchInterval:5000});const d=q.data;const selected=d?.agents.find(a=>a.agentNumber===selectedAgent)??null;
  const runsQ=useQuery({queryKey:['ivx','agent-runs','production-value',selected?.agentId??'ALL'],queryFn:()=>fetchRuns(selected?.agentId??null),enabled:Boolean(d),refetchInterval:30000});
  const refresh=useCallback(()=>{void q.refetch();void runsQ.refetch()},[q,runsQ]);const hourlyRate=Math.max(0,Number.parseFloat(rateText)||0);
  const analytics=useMemo(()=>{const start=periodStart(period);const rows=(runsQ.data??[]).filter(r=>{if(selectedAgent!==null&&r.agentNumber!==selectedAgent)return false;const t=Date.parse(r.startTime??r.endTime??'');if(!Number.isFinite(t)||t<start)return false;return Array.isArray(r.evidence)&&r.evidence.length>0&&Number(r.durationMs??0)>0;});const byDay=new Map<string,{ms:number;runs:number}>();let totalMs=0;for(const r of rows){const ms=Math.max(0,Number(r.durationMs??0));totalMs+=ms;const date=new Date(r.startTime??r.endTime??Date.now()).toISOString().slice(0,10);const prev=byDay.get(date)??{ms:0,runs:0};byDay.set(date,{ms:prev.ms+ms,runs:prev.runs+1});}const daily:DayValue[]=[...byDay.entries()].map(([date,v])=>({date,hours:v.ms/3600000,value:v.ms/3600000*hourlyRate,runs:v.runs})).sort((a,b)=>b.date.localeCompare(a.date));const hours=totalMs/3600000;return {hours,value:hours*hourlyRate,runs:rows.length,daily};},[runsQ.data,selectedAgent,period,hourlyRate]);
  const visibleAgents=selectedAgent===null?(d?.agents??[]):selected?[selected]:[];const selectPrev=()=>setSelectedAgent(v=>v===null?112:Math.max(1,v-1));const selectNext=()=>setSelectedAgent(v=>v===null?1:Math.min(112,v+1));
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={q.isFetching||runsQ.isFetching} onRefresh={refresh} tintColor={Colors.text}/> }>
    <Text style={s.title}>Autonomous + 112 IA — Work & Production Value</Text><Text style={s.sub}>Live 24h control plus selectable historical IA-hours and owner-defined production value. Only run records with execution evidence are counted.</Text>
    {q.isError?<View style={s.error}><Text style={s.errorText}>{q.error instanceof Error?q.error.message:'Failed to load ledger.'}</Text></View>:null}{runsQ.isError?<View style={s.error}><Text style={s.errorText}>{runsQ.error instanceof Error?runsQ.error.message:'Failed to load run history.'}</Text></View>:null}
    {d?<><View style={s.summary} testID="autonomous-24h-timer"><View style={s.row}><Text style={s.agent}>AUTONOMOUS · Manager</Text><Text style={s.status}>{d.autonomous.status}</Text></View><Text style={s.line}>Start {when(d.autonomous.workStartedAt)} · End {d.autonomous.running?'RUNNING':when(d.autonomous.workEndedAt)}</Text><Text style={s.line}>24h productive {d.autonomous.productiveHours24h.toFixed(2)}h · idle {d.autonomous.idleHours24h.toFixed(2)}h · coverage {d.autonomous.coveragePercent24h.toFixed(2)}%</Text><Text style={s.line}>Active managed executions {d.autonomous.activeManagedExecutions}</Text><Text style={s.small}>Window {when(d.timerWindow.startAt)} → {when(d.timerWindow.endAt)}</Text></View>
    <View style={s.analytics} testID="ia-production-value-audit"><Text style={s.sectionTitle}>IA Production Value Audit</Text><View style={s.selectorRow}><Pressable style={[s.chip,selectedAgent===null&&s.chipOn]} onPress={()=>setSelectedAgent(null)}><Text style={s.chipText}>ALL 112</Text></Pressable><Pressable style={s.chip} onPress={selectPrev}><Text style={s.chipText}>‹ IA</Text></Pressable><View style={s.agentPick}><Text style={s.agentPickText}>{selectedAgent===null?'FULL TEAM':`IA-${String(selectedAgent).padStart(3,'0')}`}</Text></View><Pressable style={s.chip} onPress={selectNext}><Text style={s.chipText}>IA ›</Text></Pressable></View>{selected?<Text style={s.small}>{selected.agentName} · {selected.role||'role n/a'}</Text>:<Text style={s.small}>Aggregate production across all 112 IA</Text>}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.periodRow}>{PERIODS.map(p=><Pressable key={p} style={[s.periodChip,period===p&&s.chipOn]} onPress={()=>setPeriod(p)}><Text style={s.chipText}>{p}</Text></Pressable>)}</ScrollView><View style={s.rateRow}><Text style={s.line}>Production value / productive IA-hour $</Text><TextInput value={rateText} onChangeText={setRateText} keyboardType="decimal-pad" style={s.rateInput} selectTextOnFocus testID="production-hourly-rate" /></View><View style={s.kpiRow}><View style={s.kpi}><Text style={s.kpiValue}>{analytics.hours.toFixed(2)}h</Text><Text style={s.small}>evidence-backed hours</Text></View><View style={s.kpi}><Text style={s.kpiValue}>{money(analytics.value)}</Text><Text style={s.small}>production value</Text></View><View style={s.kpi}><Text style={s.kpiValue}>{analytics.runs}</Text><Text style={s.small}>real runs</Text></View></View><Text style={s.small}>Value = evidence-backed productive hours × owner-entered $/hour. Internal production-value estimate, not booked revenue.</Text><Text style={s.dayTitle}>Day by day</Text>{analytics.daily.length?analytics.daily.slice(0,366).map(day=><View key={day.date} style={s.dayRow}><Text style={s.dayDate}>{day.date}</Text><Text style={s.dayMetric}>{day.hours.toFixed(2)}h</Text><Text style={s.dayMoney}>{money(day.value)}</Text><Text style={s.dayRuns}>{day.runs} runs</Text></View>):<Text style={s.small}>No evidence-backed run time in this selected range.</Text>}</View>
    <View style={s.summary}><Text style={s.line}>Agents {d.totals.totalAgents} · Active {d.totals.active} · Idle {d.totals.idle} · Blocked {d.totals.blocked}</Text><Text style={s.line}>Coding {d.totals.coding} · Testing {d.totals.testing} · CI {d.totals.waitingCi} · Deploying {d.totals.deploying}</Text><Text style={s.line}>24h productive {d.totals.agentHours24h.toFixed(2)} IA-hours · Idle {d.totals.idleHours24h.toFixed(2)} IA-hours</Text><Text style={s.line}>Commits {d.totals.commits24h} · PRs {d.totals.prs24h} · Merges {d.totals.merges24h} · Deploys {d.totals.deploys24h}</Text><Text style={s.small}>Measured {new Date(d.timerMeasuredAt).toLocaleString()} · {d.marker}</Text></View>
    {visibleAgents.map(a=><View key={a.agentNumber} style={s.card} testID={`real-ledger-ia-${a.agentNumber}`}><View style={s.row}><Text style={s.agent}>IA-{String(a.agentNumber).padStart(3,'0')} · {a.agentName}</Text><Text style={s.status}>{a.status}</Text></View><Text style={s.small}>{a.role||'role n/a'} · {a.workstream}</Text><Text style={s.task}>Task: {a.task||a.lastCompletedTask||'No measured task'}</Text><Text style={s.line}>Start {when(a.timer.workStartedAt)} · End {a.timer.running?'RUNNING':when(a.timer.workEndedAt)}</Text><Text style={s.line}>Current task {a.timer.currentTaskElapsedHours.toFixed(2)}h · 24h total {a.timer.productiveHours24h.toFixed(2)}h · idle {a.timer.idleHours24h.toFixed(2)}h</Text><Text style={s.small}>Evidence {a.evidenceState} · QA {a.qualityState} · window {when(a.timer.windowStartAt)} → {when(a.timer.windowEndAt)}</Text><Text style={s.small}>Commit {sha(a.commitSha)} · PR {a.prNumber??'—'} · Run {a.githubRunId??'—'} · Deploy {a.deployId??'—'}</Text>{a.filesChanged?.length?<Text style={s.small}>Files: {a.filesChanged.slice(0,4).join(', ')}{a.filesChanged.length>4?' …':''}</Text>:null}{a.blocker?<Text style={s.blocker}>Blocker: {a.blocker}</Text>:null}</View>)}<Text style={s.small}>{d.timerPolicy}</Text><Text style={s.small}>{d.policy}</Text></>:<Text style={s.loading}>Loading real production evidence…</Text>}
  </ScrollView>;
}

const s=StyleSheet.create({page:{flex:1,backgroundColor:Colors.background},content:{padding:16,paddingBottom:60},title:{color:Colors.text,fontSize:24,fontWeight:'800'},sub:{color:Colors.muted??'#94a3b8',marginTop:6,marginBottom:14},summary:{backgroundColor:'#15151F',borderColor:'#2A2A38',borderWidth:1,borderRadius:14,padding:14,marginBottom:14},analytics:{backgroundColor:'#15151F',borderColor:'#2A2A38',borderWidth:1,borderRadius:14,padding:14,marginBottom:14},sectionTitle:{color:Colors.text,fontSize:18,fontWeight:'900'},line:{color:Colors.text,fontSize:13,marginTop:5},small:{color:Colors.muted??'#94a3b8',fontSize:12,marginTop:4},card:{backgroundColor:'#11131A',borderColor:'#262A36',borderWidth:1,borderRadius:12,padding:12,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between',gap:8},agent:{color:Colors.text,fontWeight:'800',fontSize:15,flex:1},status:{color:Colors.primary,fontWeight:'800',fontSize:12},task:{color:Colors.text,fontSize:13,marginTop:7},blocker:{color:Colors.error??'#FF4D4D',fontSize:12,marginTop:6,fontWeight:'700'},loading:{color:Colors.text,paddingVertical:30,textAlign:'center'},error:{backgroundColor:'#351616',padding:12,borderRadius:10,marginBottom:12},errorText:{color:Colors.error??'#FF4D4D',fontWeight:'700'},selectorRow:{flexDirection:'row',alignItems:'center',gap:8,marginTop:12},chip:{borderWidth:1,borderColor:'#343847',paddingVertical:8,paddingHorizontal:11,borderRadius:10,backgroundColor:'#11131A'},chipOn:{borderColor:Colors.primary,backgroundColor:'#202633'},chipText:{color:Colors.text,fontSize:12,fontWeight:'800'},agentPick:{flex:1,minWidth:90,alignItems:'center',paddingVertical:8,borderRadius:10,backgroundColor:'#0E1017'},agentPickText:{color:Colors.text,fontWeight:'900',fontSize:13},periodRow:{gap:8,paddingVertical:12},periodChip:{borderWidth:1,borderColor:'#343847',paddingVertical:8,paddingHorizontal:14,borderRadius:10,backgroundColor:'#11131A'},rateRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},rateInput:{minWidth:100,color:Colors.text,borderWidth:1,borderColor:'#343847',borderRadius:10,paddingHorizontal:10,paddingVertical:7,textAlign:'right',backgroundColor:'#0E1017'},kpiRow:{flexDirection:'row',gap:8,marginTop:12},kpi:{flex:1,backgroundColor:'#0E1017',borderRadius:10,padding:10},kpiValue:{color:Colors.text,fontSize:17,fontWeight:'900'},dayTitle:{color:Colors.text,fontSize:14,fontWeight:'900',marginTop:14,marginBottom:4},dayRow:{flexDirection:'row',alignItems:'center',paddingVertical:8,borderTopWidth:1,borderTopColor:'#242836'},dayDate:{color:Colors.text,width:92,fontSize:12,fontWeight:'700'},dayMetric:{color:Colors.text,width:70,fontSize:12,textAlign:'right'},dayMoney:{color:Colors.primary,flex:1,fontSize:12,fontWeight:'900',textAlign:'right'},dayRuns:{color:Colors.muted??'#94a3b8',width:70,fontSize:11,textAlign:'right'}});