import React, { useCallback, useMemo, useState } from 'react';
import { ScrollView, View, Text, StyleSheet, RefreshControl, Pressable } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import Colors from '@/constants/colors';
import { getIVXAccessToken, IVX_CANONICAL_API_BASE_URL } from '@/lib/ivx-supabase-client';

type Totals={totalAgents:number;active:number;idle:number;blocked:number;coding:number;testing:number;waitingCi:number;deploying:number;complete:number;commits24h:number;prs24h:number;merges24h:number;deploys24h:number;agentHours24h:number;idleHours24h:number;idleWithSafeBacklog:number};
type Timer={running:boolean;workStartedAt:string|null;workEndedAt:string|null;currentTaskElapsedMs:number;currentTaskElapsedSeconds:number;currentTaskElapsedMinutes:number;currentTaskElapsedHours:number;windowStartAt:string;windowEndAt:string;productiveMs24h:number;productiveHours24h:number;idleMs24h:number;idleHours24h:number;measuredAt:string};
type Agent={agentNumber:number;agentId:string;agentName:string;role:string|null;task:string|null;workstream:string;githubRunId:number|null;prNumber:number|null;commitSha:string|null;deployId:string|null;status:string;blocker:string|null;filesChanged:string[];lastCompletedTask:string|null;productiveMs24h:number;idleMs24h:number;qualityState:string;evidenceState:string;timer:Timer};
type AutonomousTimer={id:string;name:string;status:string;running:boolean;workStartedAt:string|null;workEndedAt:string|null;windowStartAt:string;windowEndAt:string|null;productiveMs24h:number;productiveHours24h:number;idleMs24h:number;idleHours24h:number;coveragePercent24h:number;activeManagedExecutions:number;measuredAt:string;evidencePolicy:string};
type Resp={ok:boolean;marker:string;generatedAt:string;rowCount:number;systemRowCount:number;timerMeasuredAt:string;timerWindow:{startAt:string;endAt:string;durationHours:number};totals:Totals;autonomous:AutonomousTimer;agents:Agent[];policy:string;timerPolicy:string};
type RunRecord={runId:string;agentId:string;agentNumber:number;startTime?:string|null;endTime?:string|null;durationMs?:number|null;finalStatus?:string|null;evidence?:unknown[]};
type RunResp={ok:boolean;records?:RunRecord[]};
type PeriodKey='1D'|'7D'|'30D'|'90D'|'1Y'|'ALL';
type DayValue={date:string;hours:number;value100:number;value150:number;runs:number};

const sha=(v:string|null)=>v?v.slice(0,8):'—';
const when=(v:string|null)=>v?new Date(v).toLocaleString():'—';
const money=(v:number)=>`$${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const clock=(ms:number)=>{const total=Math.max(0,Math.floor(ms/1000));const h=Math.floor(total/3600);const m=Math.floor((total%3600)/60);const s=total%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;};
const productionValues=(ms:number)=>{const hours=Math.max(0,ms)/3600000;return {hours,value100:hours*100,value150:hours*150};};
const PERIODS:PeriodKey[]=['1D','7D','30D','90D','1Y','ALL'];
const periodStart=(key:PeriodKey)=>{if(key==='ALL')return 0;const days=key==='1D'?1:key==='7D'?7:key==='30D'?30:key==='90D'?90:365;return Date.now()-days*24*60*60*1000;};

async function authHeaders(){const token=await getIVXAccessToken();if(!token)throw new Error('Owner session required.');return {Authorization:`Bearer ${token}`,Accept:'application/json'};}
async function fetchLedger():Promise<Resp>{const r=await fetch(`${IVX_CANONICAL_API_BASE_URL}/api/ivx/autonomous/agent-ledger`,{headers:await authHeaders()});const b=await r.json().catch(()=>({})) as Partial<Resp>&{error?:string};if(!r.ok||b.ok!==true)throw new Error(b.error||`Ledger HTTP ${r.status}`);if(b.rowCount!==112||!Array.isArray(b.agents)||b.agents.length!==112)throw new Error('Ledger integrity failure: expected exactly 112 IA rows.');if(!b.autonomous)throw new Error('Ledger integrity failure: Autonomous timer missing.');return b as Resp;}
async function fetchRuns(agentId:string|null):Promise<RunRecord[]>{const path=agentId?`/api/ivx/agents/runs/${encodeURIComponent(agentId)}?limit=10000`:'/api/ivx/agents/runs?limit=10000';const r=await fetch(`${IVX_CANONICAL_API_BASE_URL}${path}`,{headers:await authHeaders()});const b=await r.json().catch(()=>({})) as RunResp&{error?:string};if(!r.ok||b.ok!==true)throw new Error(b.error||`Run history HTTP ${r.status}`);return Array.isArray(b.records)?b.records:[];}

export default function AgentLedgerScreen(){
  const [selectedAgent,setSelectedAgent]=useState<number|null>(null);const [period,setPeriod]=useState<PeriodKey>('1D');
  const q=useQuery({queryKey:['ivx','agent-ledger','live'],queryFn:fetchLedger,refetchInterval:1000});const d=q.data;const selected=d?.agents.find(a=>a.agentNumber===selectedAgent)??null;
  const runsQ=useQuery({queryKey:['ivx','agent-runs','production-value',selected?.agentId??'ALL'],queryFn:()=>fetchRuns(selected?.agentId??null),enabled:Boolean(d),refetchInterval:30000});
  const refresh=useCallback(()=>{void q.refetch();void runsQ.refetch()},[q,runsQ]);
  const analytics=useMemo(()=>{const start=periodStart(period);const rows=(runsQ.data??[]).filter(r=>{if(selectedAgent!==null&&r.agentNumber!==selectedAgent)return false;const t=Date.parse(r.startTime??r.endTime??'');if(!Number.isFinite(t)||t<start)return false;return Array.isArray(r.evidence)&&r.evidence.length>0&&Number(r.durationMs??0)>0&&!['FAILED','BLOCKED'].includes(String(r.finalStatus??'').toUpperCase());});const byDay=new Map<string,{ms:number;runs:number}>();let totalMs=0;for(const r of rows){const ms=Math.max(0,Number(r.durationMs??0));totalMs+=ms;const date=new Date(r.startTime??r.endTime??Date.now()).toISOString().slice(0,10);const prev=byDay.get(date)??{ms:0,runs:0};byDay.set(date,{ms:prev.ms+ms,runs:prev.runs+1});}const daily:DayValue[]=[...byDay.entries()].map(([date,v])=>({date,hours:v.ms/3600000,value100:v.ms/3600000*100,value150:v.ms/3600000*150,runs:v.runs})).sort((a,b)=>b.date.localeCompare(a.date));return {ms:totalMs,...productionValues(totalMs),runs:rows.length,daily};},[runsQ.data,selectedAgent,period]);
  const visibleAgents=selectedAgent===null?(d?.agents??[]):selected?[selected]:[];const selectPrev=()=>setSelectedAgent(v=>v===null?112:Math.max(1,v-1));const selectNext=()=>setSelectedAgent(v=>v===null?1:Math.min(112,v+1));
  const autonomousValue=d?productionValues(d.autonomous.productiveMs24h):productionValues(0);
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={q.isFetching||runsQ.isFetching} onRefresh={refresh} tintColor={Colors.text}/> }>
    <Text style={s.title}>Autonomous + 112 IA — Production Timer</Text><Text style={s.sub}>Evidence-backed production only. BLOCKED/FAILED/waiting time never becomes productive value.</Text>
    {q.isError?<View style={s.error}><Text style={s.errorText}>{q.error instanceof Error?q.error.message:'Failed to load ledger.'}</Text></View>:null}
    {d?<><View style={s.summary} testID="autonomous-24h-timer"><View style={s.row}><Text style={s.agent}>AUTONOMOUS · Manager</Text><Text style={s.status}>{d.autonomous.status}</Text></View><Text style={s.line}>Start {when(d.autonomous.workStartedAt)} · End {d.autonomous.running?'RUNNING':when(d.autonomous.workEndedAt)}</Text><Text style={s.timer}>24h {clock(d.autonomous.productiveMs24h)}</Text><Text style={s.line}>{Math.floor(d.autonomous.productiveMs24h/1000).toLocaleString()} sec · {(d.autonomous.productiveMs24h/60000).toFixed(2)} min · {d.autonomous.productiveHours24h.toFixed(4)} h</Text><Text style={s.value}>@ $100/h {money(autonomousValue.value100)} · @ $150/h {money(autonomousValue.value150)}</Text><Text style={s.small}>Idle {clock(d.autonomous.idleMs24h)} · coverage {d.autonomous.coveragePercent24h.toFixed(2)}% · active managed executions {d.autonomous.activeManagedExecutions}</Text></View>
    <View style={s.analytics}><Text style={s.sectionTitle}>Production Value Audit</Text><View style={s.selectorRow}><Pressable style={[s.chip,selectedAgent===null&&s.chipOn]} onPress={()=>setSelectedAgent(null)}><Text style={s.chipText}>ALL 112</Text></Pressable><Pressable style={s.chip} onPress={selectPrev}><Text style={s.chipText}>‹ IA</Text></Pressable><View style={s.agentPick}><Text style={s.agentPickText}>{selectedAgent===null?'FULL TEAM':`IA-${String(selectedAgent).padStart(3,'0')}`}</Text></View><Pressable style={s.chip} onPress={selectNext}><Text style={s.chipText}>IA ›</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.periodRow}>{PERIODS.map(p=><Pressable key={p} style={[s.periodChip,period===p&&s.chipOn]} onPress={()=>setPeriod(p)}><Text style={s.chipText}>{p}</Text></Pressable>)}</ScrollView><Text style={s.timer}>{clock(analytics.ms)}</Text><Text style={s.line}>{Math.floor(analytics.ms/1000).toLocaleString()} sec · {(analytics.ms/60000).toFixed(2)} min · {analytics.hours.toFixed(4)} h · {analytics.runs} runs</Text><Text style={s.value}>@ $100/h {money(analytics.value100)}</Text><Text style={s.value}>@ $150/h {money(analytics.value150)}</Text>{analytics.daily.slice(0,366).map(day=><View key={day.date} style={s.dayRow}><Text style={s.dayDate}>{day.date}</Text><Text style={s.dayMetric}>{day.hours.toFixed(3)}h</Text><Text style={s.dayMoney}>{money(day.value100)} / {money(day.value150)}</Text></View>)}</View>
    <View style={s.summary}><Text style={s.line}>Agents {d.totals.totalAgents} · Active {d.totals.active} · Idle {d.totals.idle} · Blocked {d.totals.blocked}</Text><Text style={s.line}>Coding {d.totals.coding} · Testing {d.totals.testing} · CI {d.totals.waitingCi} · Deploying {d.totals.deploying}</Text><Text style={s.line}>24h productive {d.totals.agentHours24h.toFixed(4)} IA-hours · Idle {d.totals.idleHours24h.toFixed(2)} IA-hours</Text></View>
    {visibleAgents.map(a=>{const v=productionValues(a.timer.productiveMs24h);return <View key={a.agentNumber} style={s.card} testID={`real-ledger-ia-${a.agentNumber}`}><View style={s.row}><Text style={s.agent}>IA-{String(a.agentNumber).padStart(3,'0')} · {a.agentName}</Text><Text style={s.status}>{a.status}</Text></View><Text style={s.small}>{a.role||'role n/a'} · {a.workstream}</Text><Text style={s.task}>Task: {a.task||a.lastCompletedTask||'No measured task'}</Text><Text style={s.line}>Start {when(a.timer.workStartedAt)} · End {a.timer.running?'RUNNING':when(a.timer.workEndedAt)}</Text><Text style={s.timer}>Current {clock(a.timer.currentTaskElapsedMs)} · 24h {clock(a.timer.productiveMs24h)}</Text><Text style={s.line}>Current: {a.timer.currentTaskElapsedSeconds.toLocaleString()} sec · {a.timer.currentTaskElapsedMinutes.toLocaleString()} min · {a.timer.currentTaskElapsedHours.toFixed(4)} h</Text><Text style={s.line}>Production 24h: {Math.floor(a.timer.productiveMs24h/1000).toLocaleString()} sec · {(a.timer.productiveMs24h/60000).toFixed(2)} min · {a.timer.productiveHours24h.toFixed(4)} h</Text><Text style={s.value}>@ $100/h {money(v.value100)} · @ $150/h {money(v.value150)}</Text><Text style={s.small}>Evidence {a.evidenceState} · QA {a.qualityState} · Commit {sha(a.commitSha)} · PR {a.prNumber??'—'} · Run {a.githubRunId??'—'}</Text>{a.blocker?<Text style={s.blocker}>Blocker: {a.blocker}</Text>:null}</View>;})}<Text style={s.small}>{d.timerPolicy}</Text><Text style={s.small}>{d.policy}</Text></>:<Text style={s.loading}>Loading real production evidence…</Text>}
  </ScrollView>;
}

const s=StyleSheet.create({page:{flex:1,backgroundColor:Colors.background},content:{padding:16,paddingBottom:60},title:{color:Colors.text,fontSize:24,fontWeight:'800'},sub:{color:Colors.muted??'#94a3b8',marginTop:6,marginBottom:14},summary:{backgroundColor:'#15151F',borderColor:'#2A2A38',borderWidth:1,borderRadius:14,padding:14,marginBottom:14},analytics:{backgroundColor:'#15151F',borderColor:'#2A2A38',borderWidth:1,borderRadius:14,padding:14,marginBottom:14},sectionTitle:{color:Colors.text,fontSize:18,fontWeight:'900'},line:{color:Colors.text,fontSize:13,marginTop:5},timer:{color:Colors.text,fontSize:19,fontWeight:'900',marginTop:8},value:{color:Colors.primary,fontSize:14,fontWeight:'900',marginTop:5},small:{color:Colors.muted??'#94a3b8',fontSize:12,marginTop:4},card:{backgroundColor:'#11131A',borderColor:'#262A36',borderWidth:1,borderRadius:12,padding:12,marginBottom:10},row:{flexDirection:'row',justifyContent:'space-between',gap:8},agent:{color:Colors.text,fontWeight:'800',fontSize:15,flex:1},status:{color:Colors.primary,fontWeight:'800',fontSize:12},task:{color:Colors.text,fontSize:13,marginTop:7},blocker:{color:Colors.error??'#FF4D4D',fontSize:12,marginTop:6,fontWeight:'700'},loading:{color:Colors.text,paddingVertical:30,textAlign:'center'},error:{backgroundColor:'#351616',padding:12,borderRadius:10,marginBottom:12},errorText:{color:Colors.error??'#FF4D4D',fontWeight:'700'},selectorRow:{flexDirection:'row',alignItems:'center',gap:8,marginTop:12},chip:{borderWidth:1,borderColor:'#343847',paddingVertical:8,paddingHorizontal:11,borderRadius:10,backgroundColor:'#11131A'},chipOn:{borderColor:Colors.primary,backgroundColor:'#202633'},chipText:{color:Colors.text,fontSize:12,fontWeight:'800'},agentPick:{flex:1,minWidth:90,alignItems:'center',paddingVertical:8,borderRadius:10,backgroundColor:'#0E1017'},agentPickText:{color:Colors.text,fontWeight:'900',fontSize:13},periodRow:{gap:8,paddingVertical:12},periodChip:{borderWidth:1,borderColor:'#343847',paddingVertical:8,paddingHorizontal:14,borderRadius:10,backgroundColor:'#11131A'},dayRow:{flexDirection:'row',alignItems:'center',paddingVertical:8,borderTopWidth:1,borderTopColor:'#242836'},dayDate:{color:Colors.text,width:92,fontSize:12,fontWeight:'700'},dayMetric:{color:Colors.text,width:75,fontSize:12,textAlign:'right'},dayMoney:{color:Colors.primary,flex:1,fontSize:12,fontWeight:'900',textAlign:'right'}});