-- Isolated acceptance schema. Never apply this file to a hosted project.
-- Column shapes follow the registration tables inspected on 2026-09-10.
create table public."investors" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid,
  "full_name" text default ''::text not null,
  "email" text default ''::text not null,
  "phone" text,
  "accreditation" text,
  "investment_tier" text,
  "capital_committed" numeric(14,2) default 0 not null,
  "capital_deployed" numeric(14,2) default 0 not null,
  "status" text default 'active'::text not null,
  "metadata" jsonb default '{}'::jsonb not null,
  "updated_by" uuid,
  "updated_at" timestamp with time zone default now() not null,
  "created_at" timestamp with time zone default now() not null,
  "deleted_at" timestamp with time zone,
  "deleted_by" text,
  "delete_reason" text,
  primary key ("id")
);
alter table public."investors" enable row level security;
grant all on public."investors" to service_role;
create table public."ivx_durable_documents" (
  "doc_key" text not null,
  "value" jsonb default '[]'::jsonb not null,
  "updated_at" timestamp with time zone default now() not null,
  primary key ("doc_key")
);
alter table public."ivx_durable_documents" enable row level security;
grant all on public."ivx_durable_documents" to service_role;
create table public."ivx_durable_events" (
  "id" bigint generated by default as identity not null,
  "doc_key" text not null,
  "event" jsonb not null,
  "created_at" timestamp with time zone default now() not null,
  primary key ("id")
);
alter table public."ivx_durable_events" enable row level security;
grant all on public."ivx_durable_events" to service_role;
create table public."landing_investments" (
  "id" uuid default gen_random_uuid() not null,
  "intent_id" text not null,
  "deal_id" text,
  "deal_title" text,
  "investment_type" text,
  "amount" numeric default 0,
  "ownership_pct" numeric default 0,
  "expected_roi" numeric default 0,
  "payment_method" text,
  "investor_email" text,
  "investor_id" uuid,
  "status" text default 'pending_payment'::text,
  "terms_accepted" boolean default false,
  "source" text default 'landing_page'::text,
  "created_at" timestamp with time zone default now(),
  "updated_at" timestamp with time zone default now(),
  "deleted_at" timestamp with time zone,
  "deleted_by" text,
  "delete_reason" text,
  "registration_request_id" text,
  primary key ("id")
);
alter table public."landing_investments" enable row level security;
grant all on public."landing_investments" to service_role;
create table public."members" (
  "member_id" uuid default gen_random_uuid() not null,
  "full_name" text default ''::text not null,
  "email" text default ''::text not null,
  "phone" text default ''::text not null,
  "member_type" text default 'member'::text not null,
  "source" text default 'landing_page'::text not null,
  "source_detail" text default ''::text not null,
  "verification_status" text default 'unverified'::text not null,
  "sms_verified" boolean default false not null,
  "email_verified" boolean default false not null,
  "investor_interest" text default ''::text not null,
  "preferred_zipcode" text default ''::text not null,
  "budget_range" text default ''::text not null,
  "auth_user_id" text,
  "landing_submission_id" text,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "deleted_at" timestamp with time zone,
  "deleted_by" text,
  "delete_reason" text,
  "picture_url" text default ''::text,
  "normalized_email" text,
  "enterprise_id" uuid,
  "normalized_phone" text,
  "country_code" text,
  "primary_role" text,
  "secondary_roles" jsonb default '[]'::jsonb,
  "registration_type" text default 'individual'::text,
  "registration_status" text default 'completed'::text,
  "email_verified_at" timestamp with time zone,
  "phone_verified_at" timestamp with time zone,
  "identity_status" text default 'active'::text,
  "kyc_status" text default 'not_started'::text,
  "aml_status" text default 'not_started'::text,
  "owner_review_status" text default 'not_started'::text,
  "source_channel" text,
  "data_origin" text,
  "terms_version" text,
  "privacy_version" text,
  "terms_accepted_at" timestamp with time zone,
  "audit_trace_id" text,
  "member_tier" text default 'PENDING'::text,
  "investor_status" text default 'NOT_VERIFIED'::text,
  "onboarding_phase" text default 'registration'::text,
  "classification_updated_at" timestamp with time zone,
  "classification_reason" text,
  "classification_version" text,
  "platform_access_status" text default 'verification_required'::text not null,
  "platform_access_reason" text,
  "verification_required_at" timestamp with time zone,
  "fully_verified_at" timestamp with time zone,
  primary key ("member_id"),
  unique (email)
);
alter table public."members" enable row level security;
grant all on public."members" to service_role;
create table public."profiles" (
  "id" uuid not null,
  "first_name" text,
  "last_name" text,
  "email" text,
  "phone" text,
  "country" text,
  "avatar" text,
  "kyc_status" text default 'pending'::text,
  "total_invested" numeric default 0,
  "total_returns" numeric default 0,
  "created_at" timestamp with time zone default now(),
  "updated_at" timestamp with time zone default now(),
  "role" text default 'investor'::text,
  "deleted_at" timestamp with time zone,
  "deleted_by" text,
  "delete_reason" text,
  "picture_url" text default ''::text,
  "referral_code" text,
  "vip_tier" text default 'standard'::text,
  primary key ("id")
);
alter table public."profiles" enable row level security;
grant all on public."profiles" to service_role;
create table public."wallets" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "available" numeric default 0,
  "pending" numeric default 0,
  "invested" numeric default 0,
  "total" numeric default 0,
  "currency" text default 'USD'::text,
  "created_at" timestamp with time zone default now(),
  "updated_at" timestamp with time zone default now(),
  "deleted_at" timestamp with time zone,
  "deleted_by" text,
  "delete_reason" text,
  primary key ("id")
);
alter table public."wallets" enable row level security;
grant all on public."wallets" to service_role;
grant usage, select on all sequences in schema public to service_role;
notify pgrst, 'reload schema';
